### PR TITLE
DROID Editor | Fix | Fix IME suggestions

### LINKED ISSUE #279: [Bug] Text suggestions not shown in keyboard
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When using Microsoft SwiftKey or Samsung keyboard, text suggestions aren't shown. The problem doesn't happen with Gboard.

Unexpectedly, it worked in japanese with SwiftKey

### Expected Behavior

Text suggestions should be shown in any keyboard, not just Gboard

### Steps To Reproduce

- Have Microsoft SwiftKey or Samsung keyboard installed (I haven't tested with other keyboards)
1. Open app > Go to note > Start typing
2. Use SwiftKey or Samsung keyboard
3. Expect keyboard suggestions to appear

https://github.com/anyproto/anytype-kotlin/assets/69634269/91cf92dd-896c-4572-9c5d-79bf938161c6

### Environment

```markdown
- OS: Android 13, Galaxy S23
- Version: 0.23.17 from the play store
```

### Anything else?

About the [current build instructions](https://github.com/anyproto/anytype-kotlin/blob/9e5c06d5a8c8258f2b7cb89e593f07432e4a1594/README.md#prerequisites), it would be nice telling why it needs a personal access token and amplitude API keys, if they are necessary at all

### PR DESCRIPTION
**Pull request by BrayanDSO**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

Fixes #279 

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Mobile & Desktop Screenshots/Recordings

https://github.com/anyproto/anytype-kotlin/assets/69634269/753be5a5-1a0a-4fd4-9044-499b8c51d835

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Since this project has been public only recently, here are some pain points I got while trying to contribute:

1. There is a [pre-push](https://github.com/anyproto/anytype-kotlin/blob/9ff2400d76a7ceb58b8d7a85549984e9bdba6e2d/.githooks/pre-push) hook that leads me to a link that I can't access, which would stop me from pushing if I didn't disable it
2. I can't commit if my branch doesn't have a task ID and I can't get a task ID anywhere
3. I believe that a github token shouldn't be necessary

**Comment by uburoiubu** [comment]
> Since this project has been public only recently, here are some pain points I got while trying to contribute:
> 
> 1. There is a [pre-push](https://github.com/anyproto/anytype-kotlin/blob/9ff2400d76a7ceb58b8d7a85549984e9bdba6e2d/.githooks/pre-push) hook that leads me to a link that I can't access, which would stop me from pushing if I didn't disable it
> 2. I can't commit if my branch doesn't have a task ID and I can't get a task ID anywhere
> 3. I believe that a github token shouldn't be necessary

hey, thanks for your feedback. your third point is already fixed. as to your first and the second point, let us think what we can do!

File: core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt [hunk 1]
```diff
@@ -182,7 +182,8 @@ fun Int.addDot(): String = "$this."
 
 fun EditText.multilineIme(action: Int) {
     setRawInputType(
-        InputType.TYPE_TEXT_FLAG_MULTI_LINE
+        InputType.TYPE_CLASS_TEXT
```
Comment (uburoiubu) [inline core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt:185]: i've just quickly tested this solution. the drawback, on my phone, is that pressing enter no longer creates a new text block but instead inserts newline character. could you confirm the same behavior on your side?

**Comment by uburoiubu** [comment]
related: https://community.anytype.io/t/autocorrect-does-not-work-on-android-gboard-and-samsung-keyboard/4292

File: core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt (hunk 1 above)
Comment (BrayanDSO) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt:185]: Yes, I can. I had noticed that as well and that’s why I drafted the PR. I believe that it should replicate the same behavior as the desktop version (I use Windows), which is `Return -> New block` and `Shift+Return -> New line in the same block`. I just gotta take a look in what is the default Android solution for that. I’ll see what I can do

Comment (BrayanDSO) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: Okay, got it fixed. And soft breaks still work if using an external keyboard. The thing is that the change supposedly removes multiline support (besides soft break). I could re-enable it where it is needed but I haven't found any place that had actual multiline support in the v0.24.4 release

Comment (uburoiubu) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: does your fix allow to create a new text block when pressing ENTER? will check this soon, thank you.

Comment (BrayanDSO) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: Here's a demo

https://github.com/anyproto/anytype-kotlin/assets/69634269/8ef90f7f-d4e7-453c-a797-ad427ab788ec

Comment (uburoiubu) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: looks like working solution. we'll test it and get back to you, thanks

Comment (uburoiubu) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: > in the v0.24.4 release

actually, multiline support is needed when, for instance, instead of creating a new block, you (force)insert a linebreak, so that you have one block with several line breaks. on Android, we should display these line breaks. could you test on your side also?

Comment (BrayanDSO) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: Besides `Shift+Return` with a keyboard (which I tested and work), how can I force a linebreak? Pasting and copying?

Comment (uburoiubu) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: > > in the v0.24.4 release
> 
> actually, multiline support is needed when, for instance, instead of creating a new block, you (force)insert a linebreak, so that you have one block with several line breaks. on Android, we should display these line breaks. could you test on your side also?

i've just checked, it works!

**Review by uburoiubu — APPROVED** [review]

File: core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt (hunk 1 above)
Comment (konstantiniiv) [reply core-utils/src/main/java/com/anytypeio/anytype/core_utils/ext/AndroidExtension.kt]: I have auto-correction working, and all the other functionality. We'll test it for a couple of days and consider the solution, but at first glance, it's a very useful fix. Thank you @BrayanDSO

**Comment by uburoiubu** [comment]
@BrayanDSO, thanks, welcome to the list of contributors ❤️

**Comment by fuksman** [comment]
@any contributor @BrayanDSO code
